### ISSUE TITLE
Kruize recommendations don't match with the values in grafana dashboard

### ISSUE THREAD

**Issue by chandrams** [kruize/kruize#115]
Description
Kruize recommendations don't match with the values in grafana dashboard. Below are the values
kruize recommendations API => graphana dashboard values

{
"application_name": "kruize",
"resources": {
"requests": {
"memory": "71.0MB", => 74.4 MB
"cpu": 0.3 => 0.5
},
"limits": {
"memory": "121.0MB", => 126.8 MB
"cpu": 0.3 => 1.0
}
}
},

**Comment by dinogun** [comment]
This is consistently reproducible for me. One more data point is that the kruize logs and API both match each other ... so not sure why the grafana query is different.
