### ISSUE TITLE
Test sign off for kruize release 0.7

### ISSUE THREAD

**Issue by chandrams** [kruize/kruize#131]
Here are the test scenarios tested with kruize.

| Test case  | Cluster type | Test Automation Status | Test Status | Comments |
| ------------- | ------------- |------------------|-------------|------------|
| Monitor a new App using kruize | Docker | Complete | Passed | |
|                |OpenShift| Complete | Passed | |
|                |Minikube| Complete | Passed | |
|                |ICP| Complete | Failed | #129 |
| Validate all recommendations | Docker | Complete | Passed | |
|                |OpenShift| Complete | Failed |#132|
|                |Minikube| Complete | Passed | |
|                |ICP| Complete | Failed | #129 |
| Remove an App and verify /recommendations and /listApplications | Docker | Complete | Passed |  |
|                |OpenShift| Complete | Passed | |
|                |Minikube| Complete | Passed | |
|                |ICP| Complete | Failed | #129 |
| Monitor multiple applications using kruize | Docker | Complete | Passed |  |
|                |OpenShift| Complete | Passed | |
|                |Minikube| Complete | Passed | |
|                |ICP| Complete | Failed | #129 |
| Monitor multiple instances of an application using kruize | Docker | In progress | Yet to test | Need to figure out how to use external ports in prometheus.yaml, not required for 0.7 release though |
|                | OpenShift | Complete | Passed | |
|                | Minikube | Complete | Passed | |
|                | ICP | Complete | Failed | #129 |
| Multiple kruize instances (Not supported as of now) | Docker / ICP / minikube / openshift | NA | Failed | #118
| Validate Kruize recommendations in Grafana Dashboard against values give by Rest APIs | Docker | NA (manual) | Passed | |
|  | Minikube  | NA (manual)  | Failed | #151 |
|  | ICP  | NA (manual) | Failed | |
|  | Openshift | NA (manual) | Failed |  #112  |
| Stability test to validate kruize recommendations generated are within the acceptable ranges  | Docker | Yet to start | Yet to test |  |
|                | OpenShift | Passed | | |
|                | Minikube | Yet to start | Yet to test | |
|                | ICP | Failed |#129 | |
| Validate Kruize API documentation |  | NA (manual) | Passed | |
| Validate Runtime parameters related doc updates |  | NA (manual) | Passed | Leaving ICP, I have validated this on docker, minikube, openshift|

**Comment by ShishirH** [comment]
@chandrams, the fix for the test case `Remove an App and verify /recommendations and /listApplications` is already out but not merged yet. Can you please check if that PR fixes the issue?
