### ISSUE TITLE
NodeSelector taints cause kruize installation to fail on ICP

### ISSUE THREAD

**Issue by chandrams** [kruize/kruize#16]
- Make changes to the scripts to update the kruize yaml with the latest kruize docker image built.  
- Nodeselector needs to be removed for deploying to ICP

**Comment by ShishirH** [comment]
apiVersion needs to be generalised based on Kubernetes version.
app/v1 should be used for version > 1.9.0, extensions/v1beta for earlier versions.

**Comment by chandrams** [comment]
Taint details on j9mx ICP
[root@ICP-Master ~]# kubectl describe nodes | grep -i taint
Taints:             <none>
Taints:             dedicated=infra:NoSchedule

**Comment by chandrams** [comment]
Tolerations on other pods on ICP master:
```
Tolerations:     CriticalAddonsOnly
                 dedicated:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
```

**Comment by dinogun** [comment]
This should be fixed now.

**Comment by ShishirH** [comment]
#62 removes nodeSelectors and the tolerances.

**Comment by chandrams** [comment]
This is fixed now.
