### ISSUE TITLE
Recommendations are not getting generated when we deploy kruize on power architecture

### ISSUE THREAD

**Issue by AaruniAggarwal** [kruize/kruize#164]
**Is your feature request related to a problem? Please describe.**
i want to test these 2 scenarios :
try with test pod that apparently requests too much (makes it harder to find a node to run on)
2.   Try with test pod that apparently requests too little (causes repeated eviction)
so when i am trying to deploy pod with larger limits , then pod is not coming up because of failedScheduling error that's why kruize is not generating recommendations . and if pod have lesser limits then also kruize is not showing recommendations.
{
   "application_name": "kruize",
   "resources": {
     "requests": {
       "memory": "0.0M",
       "cpu": 0.0
     },
     "limits": {
       "memory": "0.0M",
       "cpu": 0.0
     }
   }
 }
I also tried with acme-air then also application-pod didn't generate recommendations. 
**Describe the solution you'd like**
I know that If the cpu usage of the app is below a threshold, it wont generate recommendations , as Kruize did not get enough data to generate a recommendation. So I want to know what is the threshold value.

**Comment by AaruniAggarwal** [comment]
I tried this for both the scenarios: 
**Scenario -1** 
If we try with test pod that apparently requests too much (makes it harder to find a node to run on)   ->>>
Then pod will remain in Pending state with the error : FailedScheduling 
and kruize will not show anything , output for recommendations will be empty array.
_Example:_
pod.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: nginx
    resources:
      requests:
        cpu: 2
        example.com/foo: 1
      limits:
        example.com/foo: 1
```


[root@kruize-aaruni-inf kruize]# oc get pods |grep pod
my-pod                                         0/1     Pending   0          102s


[root@kruize-aaruni-inf kruize]# oc describe pod my-pod
Name:         my-pod
Namespace:    openshift-monitoring
Priority:     0
Node:         <none>
Labels:       <none>
Annotations:  openshift.io/scc: anyuid
Status:       Pending
IP:           
IPs:          <none>
Containers:
  my-container:
    Image:      nginx
    Port:       <none>
    Host Port:  <none>
    Limits:
      example.com/foo:  1
    Requests:
      cpu:              2
      example.com/foo:  1
    Environment:        <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-7w949 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  default-token-7w949:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-7w949
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/6 nodes are available: 6 Insufficient example.com/foo.
  Warning  FailedScheduling  <unknown>  default-scheduler  0/6 nodes are available: 6 Insufficient example.com/foo.

In order to check the recommendations label the pod : 
[root@kruize-aaruni-inf kruize]# oc label -n openshift-monitoring pod my-pod app.kubernetes.io/name=my-pod
pod/my-pod labeled

Get the Recommendations : 
[root@kruize-aaruni-inf kruize]# curl http://kruize-openshift-monitoring.apps.kruize-aaruni.cp.fyre.ibm.com/recommendations?application_name=my-pod
[]


**Scenario-2**
Try with test pod that apparently requests too little (causes repeated eviction)
If the cpu usage of the app is below a threshold, it wont generate recommendations , as Kruize did not get enough data to generate a recommendation. 
In our case its same ->
_pod-min.yaml ::_

```
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-min
spec:
  containers:
  - name: my-container
    image: nginx
    resources:
      requests:
        cpu: "150m"
        memory: "50Mi"
      limits:
        cpu: "500m"
        memory: "128Mi"
```
                  
[root@kruize-aaruni-inf kruize]# oc get pods |grep pod
my-pod                                         0/1     Pending   0          23m
my-pod-min                                 1/1     Running   0          37s

**Label the pod to get recommendations :**

[root@kruize-aaruni-inf kruize]# oc label -n openshift-monitoring pod my-pod-min app.kubernetes.io/name=my-pod-min
pod/my-pod-min labeled

Get the recommendations ->

[root@kruize-aaruni-inf kruize]# curl http://kruize-openshift-monitoring.apps.kruize-aaruni.cp.fyre.ibm.com/recommendations?application_name=kruize
[
  {
    "application_name": "kruize",
    "resources": {
      "requests": {
        "memory": "0.0M",
        "cpu": 0.0
      },
      "limits": {
        "memory": "0.0M",
        "cpu": 0.0
      }
    }
  }
]


[root@kruize-aaruni-inf kruize]# 
[root@kruize-aaruni-inf kruize]# curl http://kruize-openshift-monitoring.apps.kruize-aaruni.cp.fyre.ibm.com/recommendations?application_name=my-pod-min
[
  {
    "application_name": "my-pod-min",
    "resources": {
      "requests": {
        "memory": "0.0M",
        "cpu": 0.0
      },
      "limits": {
        "memory": "0.0M",
        "cpu": 0.0
      }
    }
  }
]

**Comment by dinogun** [comment]
@AaruniAggarwal Thank you for trying out kruize !

Normally we recommend that you run your pods that are being monitored by kruize with no requests and limits set (or with very high limits set). This helps kruize to understand what is the real usage and hence can recommend the right set of values.

Is there any reason why you are running with the above constraints ?

**Comment by AaruniAggarwal** [comment]
@dinogun Thanks for responding.
I tried with acme-air application in which no requests and limits were set. I added the customers in acme-air then also no recommendations were generated. 
[root@ocs-sridhar-rhceph-8d86-bastion ~]# curl http://kruize-openshift-monitoring.apps.ocs-sridhar-rhceph-8d86.ibm.com/recommendations?application_name=acmeair-customer-db
[
  {
    "application_name": "acmeair-customer-db",
    "resources": {
      "requests": {
        "memory": "0.0M",
        "cpu": 0.0
      },
      "limits": {
        "memory": "0.0M",
        "cpu": 0.0
      }
    }
  }
]
And in scenario1 , which I pasted above I set the very high limits due to which pod didn't come up. 
Yes, I was asked to test these 2 scenarios and check whether kruize is generating right recommendations or not on power (ppc64le) architecture.

**Comment by AaruniAggarwal** [comment]
That's why I wanted to know is there any specific example for these 2 scenarios with which I can test with

**Comment by AaruniAggarwal** [comment]
Any update on this issue ?

**Comment by agarwalrounak** [comment]
The two scenarios that you are trying out are not good test cases. Thus, Kruize can't give you good recommendations because of that. 
We would like to know a bit more about why are you testing these 2 specific scenarios. Any particular reasons for this?

**Comment by agarwalrounak** [comment]
Also, you can try applying load when using the acme-air application. If you run into any problems while applying load, @shruacha1234 should be able to help you out.

**Comment by AaruniAggarwal** [comment]
Again tried with acme-air and this time i added more customers . 
Earlier i was adding 10000 customers by using this command : 
`curl http://HOSTNAME:PORT_NUMBER/customer/loader/load?numCustomers=10000 `
And now I increased the customers by 10 times : 
`curl http://HOSTNAME:PORT_NUMBER/customer/loader/load?numCustomers=100000` .
And this time recommendations got generated. 
Before adding load : 
[root@kruize-inf acmeair]# curl http://kruize-openshift-monitoring.apps.kruize.cp.fyre.ibm.com/recommendations?application_name=acmeair-customer-db
```
[
{
    "application_name": "acmeair-customer-db",
    "resources": {
      "requests": {
        "memory": "0.0M",
        "cpu": 0.0
      },
      "limits": {
        "memory": "0.0M",
        "cpu": 0.0
      }
    }
  }
]
```
After adding load : 
curl http://HOSTNAME:PORT_NUMBER/customer/loader/load?numCustomers=100000 
[root@kruize-inf acmeair]# curl http://kruize-openshift-monitoring.apps.kruize.cp.fyre.ibm.com/recommendations?application_name=acmeair-customer-db
```
[
  {
    "application_name": "acmeair-customer-db",
    "resources": {
      "requests": {
        "memory": "194.6M",
        "cpu": 0.5
      },
      "limits": {
        "memory": "233.5M",
        "cpu": 1.0
      }
    }
  }
]
```
