### ISSUE TITLE
docker type: no recommendations produced

### ISSUE THREAD

**Issue by dinogun** [kruize/kruize#20]
The current prometheus query for cpu, `rate(container_cpu_usage_seconds_total{name=~"acmeair-mono-app1"}[1m])` does not return actual cpu usage data, resulting in not getting any recommendations at all.
Memory OTOH shows the correct actual usage, but still no recommendations produced.

**Comment by ShishirH** [comment]
Reproduced this even after using sum. Seems like some code changes needed, taking a closer look
