### ISSUE TITLE
Remove references to prometheus in codebase

### ISSUE THREAD

**Issue by ShishirH** [kruize/kruize#26]
The prometheus gauges used should be generalised for all monitoring agents, and no references to prometheus should be found.

**Comment by ShishirH** [comment]
Other parts of code referencing Prometheus related classes directly:
1. Variable name prometheusURL: https://github.com/kruize/kruize/blob/4c0f2794c3de04af089625727617ed3b29e803ab/src/main/java/com/kruize/collection/CollectMetrics.java#L157
and  https://github.com/kruize/kruize/blob/4c0f2794c3de04af089625727617ed3b29e803ab/src/main/java/com/kruize/collection/CollectMetrics.java#L204

2. Directly getting instance of Prometheus related classes:
https://github.com/kruize/kruize/blob/4c0f2794c3de04af089625727617ed3b29e803ab/src/main/java/com/kruize/environment/docker/DockerEnvImpl.java#L55
and
https://github.com/kruize/kruize/blob/4c0f2794c3de04af089625727617ed3b29e803ab/src/main/java/com/kruize/environment/kubernetes/KubernetesEnvImpl.java#L123
and
https://github.com/kruize/kruize/blob/4c0f2794c3de04af089625727617ed3b29e803ab/src/main/java/com/kruize/environment/kubernetes/KubernetesEnvImpl.java#L284

**Comment by ShishirH** [comment]
Will create a new layer of abstraction MonitoringAgent, and generalise all these parts of the codebase

**Comment by dinogun** [comment]
Can we use this issue to remove the prometheus references in the file [kruize.java](https://github.com/kruize/kruize/blob/master/src/main/java/com/kruize/main/Kruize.java) alone for now.
