### ISSUE TITLE
Eliminate code duplication for containers/pods

### ISSUE THREAD

**Issue by ShishirH** [kruize/kruize#36]
Code duplication present in pod and container specific classes need to be removed, and moved to a common class.

**Comment by ShishirH** [comment]
@dinogun In the Docker use case, should we be suggesting requests? Right now it just gives 0.

**Comment by dinogun** [comment]
Can you be more specific about which code is duplicated currently ?
>> @dinogun In the Docker use case, should we be suggesting requests? Right now it just gives 0.
Yes, we need to suggest `requests` in the docker case as well, and can become the basis of the initial yaml file.

**Comment by ShishirH** [comment]
The getters and setters in PodMetrics https://github.com/kruize/kruize/blob/ab41bd866aaae44f687cd96f67417d85c86cb899/src/main/java/com/kruize/metrics/PodMetrics.java#L39
and ContainerMetrics https://github.com/kruize/kruize/blob/ab41bd866aaae44f687cd96f67417d85c86cb899/src/main/java/com/kruize/metrics/ContainerMetrics.java#L28

Both PodRecommendations.java and ContainerRecommendations.java are identical
