### ISSUE TITLE
Update deploy script to not fail when pending

### ISSUE THREAD

**Issue by ShishirH** [kruize/kruize#40]
Observed that sometimes prometheus deployment stays at pending for a while until other services start running. 

So while the script says that the deployment failed, it should still be deployed after a few seconds.

Output from the script:
Error: prometheus-k8s-0 deploy failed: Pending
prometheus-k8s-0                      0/3     ContainerCreating   0          1s

**Comment by dinogun** [comment]
This is fixed now.
