### ISSUE TITLE
Add support for openshift

### ISSUE THREAD

**Issue by dinogun** [kruize/kruize#5]
Code changes and script updates to deploy kruize to openshift

**Comment by dinogun** [comment]
This should help us to deploy kruize to OpenShift -> https://docs.openshift.com/container-platform/3.11/install_config/prometheus_cluster_monitoring.html

**Comment by ShishirH** [comment]
Status:
Once script changes are merged, should work with a few caveats.
1. A service monitor is required for prometheus to pick up the metrics being exported by Kruize. However, adding additional targets to Prometheus is an explicitly unsupported operation according to the link above.
2. Bearer token is still required as of now.
