### ISSUE TITLE
Docker usecase should suggest resource requests

### ISSUE THREAD

**Issue by ShishirH** [kruize/kruize#51]
Right now, resource requests recommendations are not given when running in Docker locally, and 0 is reported instead. We should use the same algorithm to generate the recommendations for Docker.

**Comment by dinogun** [comment]
Request recommendations are now available. @chandrams please check and close.

**Comment by ShishirH** [comment]
Can confirm recommendations are being confirmed, though PR hasn't been merged. Taking a look
