### ISSUE TITLE
Update deploy script to support macOS

### ISSUE THREAD

**Issue by bharathappali** [kruize/kruize#64]
**Raising this issue in an impression that kruize is having macos support**

I was trying `kruize` in docker mode on macos and the command `./deploy.sh -c docker` prints these errors.

```
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
sed: 1: "kruize-docker-tmp.json": invalid command code k
```

**Exploration :**
Errors are specific to macos as `grep` doesn't support `-P` option which was used [here](https://github.com/kruize/kruize/blob/master/deploy.sh#L150) and `sed -i` expects an `extension` argument which is missing [here](https://github.com/kruize/kruize/blob/master/deploy.sh#L129)

**Possible workarounds for macos**
replacing `-P` with `-e` (for pattern)
adding the `extension` argument (`-e`) for `sed`

**Comment by ShishirH** [comment]
Right now the deploy scripts only work on Linux. I'm quite interested in working on the macOS compatibility because I don't think it will be too different from the Linux scripts. Can't speak for Windows though.

@dinogun
