### ISSUE TITLE
icp deploy failed as KRUIZE_DOCKER_IMAGE wasn't replaced by sed

### ISSUE THREAD

**Issue by chandrams** [kruize/kruize#73]
Tested deploy.sh by passing -i dinogun/kruize:0.6.5-rc2

sed: -e expression #1, char 37: unknown option to `s'
Info: Deploying kruize yaml to ICP cluster
error: error parsing manifests/kruize.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"KRUIZE_DOCKER_IMAGE":interface {}(nil)}
Info: Waiting for kruize to come up...

**Comment by dinogun** [comment]
Should be fixed in #77

**Comment by dinogun** [comment]
@chandrams Please confirm

**Comment by chandrams** [comment]
This is fixed now.
